In [6]:
import xgboost
print(xgboost.__version__)

3.2.0

In [7]:
# Import models and evaluation metrics
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

# Dictionary of models
models = {
    'Logistic Regression': LogisticRegression(random_state=42, max_iter=1000),
    'Random Forest': RandomForestClassifier(random_state=42),
    'XGBoost': XGBClassifier(random_state=42, eval_metric='logloss')
}

# Store results
results = []

# Train and evaluate each model
for name, model in models.items():

    # Train model
    model.fit(X_train, y_train)

    # Predictions
    y_pred = model.predict(X_test)

    # Probabilities for ROC-AUC
    y_prob = model.predict_proba(X_test)[:, 1]

    # Evaluation metrics
    results.append({
        'Model': name,
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred),
        'Recall': recall_score(y_test, y_pred),
        'F1 Score': f1_score(y_test, y_pred),
        'ROC-AUC': roc_auc_score(y_test, y_prob)
    })

# Display results
results_df = pd.DataFrame(results)

results_df.sort_values(by='ROC-AUC', ascending=False)

                 Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC
0  Logistic Regression  0.804549   0.650456  0.572193  0.608819  0.836071
2              XGBoost  0.778252   0.589080  0.548128  0.567867  0.819670
1        Random Forest  0.788202   0.623377  0.513369  0.563050  0.815628

In [8]:
results_df.sort_values(by='ROC-AUC', ascending=False)

                 Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC
0  Logistic Regression  0.804549   0.650456  0.572193  0.608819  0.836071
2              XGBoost  0.778252   0.589080  0.548128  0.567867  0.819670
1        Random Forest  0.788202   0.623377  0.513369  0.563050  0.815628

In [9]:
import joblib

joblib.dump(models['Logistic Regression'],
            '../models/churn_model.pkl')

['../models/churn_model.pkl']